[uwsgi]
http = 0.0.0.0:5000
http-websockets = true
master = true
gevent = 1000
enable-threads = true
module = app:app
#wsgi-file = /app/app.py
callable = app
lazy-apps = true
vacuum = true
buffer-size = 32768


; # General settings
; master = true
; processes = 4
; threads = 2
; gevent = 1000
; http-websockets = true

; # Socket binding
; socket = 0.0.0.0:5000
; wsgi-file = /app/app.py

; # Log settings
; ; logto = /var/log/uwsgi/uwsgi.log

; # Clean up after workers
; vacuum = true

; # Disable logging for uWSGI itself
; disable-logging = true
